apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: microservices
type: Opaque
stringData:
  # PostgreSQL User DB
  POSTGRES_USER_DB_USER: "user_db_user"
  POSTGRES_USER_DB_PASSWORD: "user_db_password"
  POSTGRES_USER_DB_NAME: "user_db"
  # PostgreSQL Order DB
  POSTGRES_ORDER_DB_USER: "order_db_user"
  POSTGRES_ORDER_DB_PASSWORD: "order_db_password"
  POSTGRES_ORDER_DB_NAME: "order_db"
  # PostgreSQL Payment DB
  POSTGRES_PAYMENT_DB_USER: "payment_db_user"
  POSTGRES_PAYMENT_DB_PASSWORD: "payment_db_password"
  POSTGRES_PAYMENT_DB_NAME: "payment_db"
  # MongoDB Product DB
  MONGO_ROOT_USERNAME: "product_db_user"
  MONGO_ROOT_PASSWORD: "product_db_password"
  MONGO_DB_NAME: "product_db"
  # RabbitMQ
  RABBITMQ_DEFAULT_USER: "rabbitmq_user"
  RABBITMQ_DEFAULT_PASS: "rabbitmq_password"



